version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: desafio-ubots
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - ./target/desafio-ubots-0.0.1-SNAPSHOT.jar:/app/desafio-ubots.jar
    command: ["java", "-jar", "/app/desafio-ubots.jar"]
    depends_on:
      redis:
        condition: service_healthy 

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local